
Epoch 1
----------------------
Traceback (most recent call last):                                              
Train Loss: 0.3654598875380144, Train Accuracy: 91.61585365853658
Val Loss: 0.5009012222290039, Val Accuracy: 21.875
Test Loss: 1.5657539367675781, Test Accuracy: 77.5
Done!

Final Model Performance:
-------------------
Loss: 1.5591718077659606, Accuracy: 77.5
Confusion Matrix
: [[361  99]
 [ 29 135]]
Sensitivity: 0.9256410256410257, Specificity: 0.5769230769230769
  File "/Users/veramazeeva/Library/CloudStorage/OneDrive-Personal/Carnegie Mellon/CompMed/project/code/cnn.py", line 306, in <module>
    main()
  File "/Users/veramazeeva/Library/CloudStorage/OneDrive-Personal/Carnegie Mellon/CompMed/project/code/cnn.py", line 301, in main
    os.mkdir(args.out_dir)
FileExistsError: [Errno 17] File exists: 'out'
